'use client';

import { motion, AnimatePresence } from 'framer-motion';
import type { Message } from '@/types';

interface AdaptiveCanvasProps {
  isOpen: boolean;
  message: Message | null;
  onClose: () => void;
}

/**
 * NEXUS Adaptive Canvas - Slide-out panel for rich artifacts
 * Renders structured JSON outputs as interactive UI
 */
export function AdaptiveCanvas({ isOpen, message, onClose }: AdaptiveCanvasProps) {
  if (!message?.metadata?.artifact_type) return null;

  const artifactType = message.metadata.artifact_type;
  const content = message.metadata.content;

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/20 backdrop-blur-sm z-40"
          />

          {/* Canvas Panel */}
          <motion.div
            initial={{ x: '100%', opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            exit={{ x: '100%', opacity: 0 }}
            transition={{ type: 'spring', stiffness: 300, damping: 30 }}
            className="fixed right-0 top-0 h-screen w-[40%] bg-white/80 backdrop-blur-2xl border-l border-white/90 shadow-2xl z-50 flex flex-col"
          >
            {/* Header */}
            <div className="p-6 border-b border-luminous-text-tertiary/10 flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-extrabold tracking-tight text-luminous-text-primary">
                  {artifactType === 'linkedin_post' ? 'LinkedIn Post' :
                   artifactType === 'report' ? 'Report' :
                   artifactType === 'chart' ? 'Chart' : 'Artifact'}
                </h2>
                <p className="text-sm text-luminous-text-secondary font-medium mt-1">
                  Generated by {message.author.name}
                </p>
              </div>
              <motion.button
                onClick={onClose}
                className="w-10 h-10 rounded-full bg-luminous-text-tertiary/10 hover:bg-luminous-text-tertiary/20 flex items-center justify-center transition-colors"
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
              >
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M12 4L4 12M4 4L12 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                </svg>
              </motion.button>
            </div>

            {/* Content Area */}
            <div className="flex-1 overflow-y-auto p-6">
              {artifactType === 'linkedin_post' && <LinkedInPostPreview content={content} />}
              {artifactType === 'report' && <ReportPreview content={content} />}
              {artifactType === 'chart' && <ChartPreview content={content} />}
              {artifactType === 'funnel_analysis' && <FunnelChartPreview content={content} />}
            </div>

            {/* Footer Actions */}
            <div className="p-6 border-t border-luminous-text-tertiary/10 flex items-center gap-3">
              <motion.button
                className="flex-1 px-4 py-3 rounded-2xl bg-luminous-accent-purple text-white font-bold shadow-luminous"
                whileHover={{ scale: 1.02, y: -2 }}
                whileTap={{ scale: 0.98 }}
              >
                Export
              </motion.button>
              <motion.button
                className="flex-1 px-4 py-3 rounded-2xl bg-white/60 backdrop-blur-xl border border-white/80 text-luminous-text-primary font-bold"
                whileHover={{ scale: 1.02, y: -2 }}
                whileTap={{ scale: 0.98 }}
              >
                Edit
              </motion.button>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}

// Artifact Renderers

interface LinkedInPostPreviewProps {
  content: any;
}

function LinkedInPostPreview({ content }: LinkedInPostPreviewProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      {/* LinkedIn Post Card */}
      <div className="bg-white/60 backdrop-blur-xl border border-white/80 rounded-3xl p-6 shadow-luminous">
        <div className="flex items-start gap-4 mb-4">
          <div className="w-12 h-12 rounded-full bg-luminous-accent-cyan flex items-center justify-center text-white font-bold">
            You
          </div>
          <div className="flex-1">
            <div className="font-bold text-luminous-text-primary">Your Name</div>
            <div className="text-xs text-luminous-text-tertiary">Professional Title • Now</div>
          </div>
        </div>

        <div className="prose prose-sm max-w-none text-luminous-text-primary whitespace-pre-wrap mb-4">
          {content.post_body}
        </div>

        {content.hashtags && (
          <div className="flex flex-wrap gap-2">
            {content.hashtags.map((tag: string, i: number) => (
              <span key={i} className="text-luminous-accent-cyan font-semibold text-sm">
                #{tag}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Metrics */}
      {content.virality_score && (
        <div className="bg-white/60 backdrop-blur-xl border border-white/80 rounded-3xl p-6 shadow-luminous">
          <h3 className="font-extrabold text-luminous-text-primary mb-4">Virality Analysis</h3>
          <div className="flex items-center gap-4">
            <div className="flex-1 h-3 bg-luminous-text-tertiary/20 rounded-full overflow-hidden">
              <motion.div
                className="h-full bg-gradient-to-r from-luminous-accent-cyan to-luminous-accent-purple"
                initial={{ width: 0 }}
                animate={{ width: `${content.virality_score * 10}%` }}
                transition={{ duration: 1, ease: 'easeOut' }}
              />
            </div>
            <span className="font-extrabold text-2xl text-luminous-accent-purple">
              {content.virality_score}/10
            </span>
          </div>
        </div>
      )}
    </motion.div>
  );
}

interface ReportPreviewProps {
  content: any;
}

function ReportPreview({ content }: ReportPreviewProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-white/60 backdrop-blur-xl border border-white/80 rounded-3xl p-8 shadow-luminous"
    >
      <h1 className="text-3xl font-extrabold tracking-tight text-luminous-text-primary mb-6">
        {content.title || 'Report'}
      </h1>
      <div className="prose prose-sm max-w-none text-luminous-text-primary">
        {content.sections?.map((section: any, i: number) => (
          <div key={i} className="mb-6">
            <h2 className="text-xl font-extrabold tracking-tight mb-3">{section.heading}</h2>
            <p className="font-medium">{section.body}</p>
          </div>
        ))}
      </div>
    </motion.div>
  );
}

interface ChartPreviewProps {
  content: any;
}

function ChartPreview({ content }: ChartPreviewProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-white/60 backdrop-blur-xl border border-white/80 rounded-3xl p-8 shadow-luminous"
    >
      <h2 className="text-2xl font-extrabold tracking-tight text-luminous-text-primary mb-6">
        {content.title || 'Chart'}
      </h2>
      <div className="h-64 flex items-center justify-center border-2 border-dashed border-luminous-text-tertiary/30 rounded-2xl">
        <p className="text-luminous-text-tertiary font-medium">
          Chart visualization would render here
        </p>
      </div>
    </motion.div>
  );
}

interface FunnelChartPreviewProps {
  content: any;
}

function FunnelChartPreview({ content }: FunnelChartPreviewProps) {
  const stages = content.stages || [];

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      <div className="bg-white/60 backdrop-blur-xl border border-white/80 rounded-3xl p-8 shadow-luminous">
        <h2 className="text-2xl font-extrabold tracking-tight text-luminous-text-primary mb-8">
          Funnel Analysis
        </h2>

        <div className="space-y-4">
          {stages.map((stage: any, i: number) => {
            const maxCount = stages[0]?.count || 1;
            const widthPercent = (stage.count / maxCount) * 100;

            return (
              <div key={i}>
                <div className="flex items-center justify-between mb-2">
                  <span className="font-bold text-luminous-text-primary">{stage.name}</span>
                  <span className="text-sm text-luminous-text-secondary font-medium">
                    {stage.count.toLocaleString()} ({stage.conversion_rate}%)
                  </span>
                </div>
                <div className="h-12 bg-luminous-text-tertiary/10 rounded-2xl overflow-hidden">
                  <motion.div
                    className="h-full bg-gradient-to-r from-luminous-accent-cyan to-luminous-accent-purple flex items-center justify-center text-white font-bold"
                    initial={{ width: 0 }}
                    animate={{ width: `${widthPercent}%` }}
                    transition={{ duration: 0.8, delay: i * 0.1 }}
                  >
                    {widthPercent > 20 && `${stage.conversion_rate}%`}
                  </motion.div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </motion.div>
  );
}
